	ALTER PROCEDURE [dbo].[Insert_Employee]
	@firstname nvarchar(30),
	--@lastname nvarchar(30),
	--@jobid int
	AS
	BEGIN 
		INSERT into Employee (Firstname, Lastname, JobId)   -- don't list id because its autogenerated
			VALUES (@firstname, @lastname, @jobid)
			WHERE Firstname = @search
	END
	GO
	EXEC Employee_by_Firstname @firstname = 'Amy';
