
-- always start with this 'bare bones' form

/**CREATE PROCEDURE Insert_Employee
	@firstname nvarchar(30),
	@lastname nvarchar(30).
	@jobid int
	AS
	BEGIN 

	END
	*/

	
-- always start with this form
CREATE PROCEDURE Insert_Employee
	@firstname nvarchar(30),
	@lastname nvarchar(30),
	@jobid int
	AS
	BEGIN 
		INSERT into Employee (Firstname, Lastname, JobId)   -- don't list id because its autogenerated
			VALUES (@firstname, @lastname, @jobid)
	END